name: Deploy
description: "Deploy testapp to a given environment"
inputs:
  commit_directly:
    required: true
    description: "Whether to commit directly to the environment or not. If not set, it will be deployed as a PR."
  deployment_environment:
    required: true
    description: "The environment to deploy to"
  github_sha:
    required: true
    description: "The sha of the commit to deploy"
  INFRASTRUCTURE_REPOSITORY_USERNAME:
    required: true
    description: "The repository username"
  INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN:
    required: true
    description: "The repository personal access token"

runs:
  using: "composite"
  steps:
    - name: Setup actions
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Render
      run: ./.github/scripts/install_render_ci.sh
      shell: bash


    - name: Deploy Testapp
      env:
        GH_TOKEN: ${{ inputs.INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
        COMMIT_DIRECTLY: ${{ inputs.commit_directly }}
        ENVIRONMENT: ${{ inputs.deployment_environment }}
        SERVICE: app
        TAG: ${{ inputs.github_sha }}
        INFRASTRUCTURE_REPOSITORY_USERNAME: ${{ inputs.INFRASTRUCTURE_REPOSITORY_USERNAME }}
        INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN: ${{ inputs.INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN }}
      run: |
        ./.github/scripts/deploy_image_tag.sh \
          -c $COMMIT_DIRECTLY \
          -e $ENVIRONMENT \
          -s $SERVICE \
          -t $TAG \
          -u $INFRASTRUCTURE_REPOSITORY_USERNAME \
          -p $INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN
      shell: bash