name: main
on:
  push:
    branches:
      - main

concurrency:
  group: cicd-main

env:
  DOCKER_HUB_REPOSITORY: dpm1217/test-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit SHA
        id: vars
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_REPOSITORY }}:latest-${{ steps.vars.outputs.sha }}
  
  deploy:
    needs:
      - build_and_push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - name: "Deploy"
        uses: ./.github/actions/deploy
        with:
          commit_directly: true
          deployment_environment: staging
          github_sha: ${{ github.sha }}
          INFRASTRUCTURE_REPOSITORY_USERNAME: danmurphy1217 # using personal username for now
          INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN: ${{ secrets.INFRASTRUCTURE_REPOSITORY_PERSONAL_ACCESS_TOKEN }}